server:
  port: 8808
logging:
  level: info
  level.io.github.hylexus: debug
jt808:
  entity-scan:
    enabled: true
    base-packages: io.github.hylexus.jt808.server.msg.req
    enable-builtin-entity: true
  print-component-statistics: true
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
  msg-processor:
    thread-pool:
      core-pool-size: 4
      maximum-pool-size: 4
      keep-alive-time: 60s
      blocking-queue-size: 20
      thread-name-format: '808-msg-processor-%d'

