jt808:
  print-component-statistics: true
  protocol:
    version: auto_detection
    max-frame-length: 1024
  server:
    port: 6808
    boss-thread-count: 0
    worker-thread-count: 0
    idle-state-handler:
      enabled: true
      reader-idle-time: 20m
      writer-idle-time: 20m
      all-idle-time: 20m
  entity-scan:
    enabled: true
    enable-builtin-entity: true
    base-packages:
    register-builtin-request-msg-converters: true
  handler-scan:
    enabled: true
    base-packages:
    register-builtin-msg-handlers: true
  exception-handler-scan:
    enabled: true
    base-packages: ${jt808.handler-scan.base-packages:}
    register-builtin-exception-handlers: true
  msg-processor:
    thread-pool:
      # core-pool-size: Runtime.getRuntime().availableProcessors() + 1
      # maximum-pool-size: 2 * corePoolSize
      keep-alive-time: 60s
      blocking-queue-size: 100
      thread-name-format: '808-msg-processor-%d'
logging:
  level.io.github.hylexus: debug
  level.jt-808.msg.req.decoder: info
  level.jt-808.msg.req.handler.abstract-msg-handler: debug
  level.jt-808.channel.handler.adapter: debug